import 'package:flutter/material.dart';
import 'package:zenon_syrius_wallet_flutter/rearchitecture/utils/utils.dart';
import 'package:zenon_syrius_wallet_flutter/utils/app_colors.dart';
import 'package:zenon_syrius_wallet_flutter/utils/global.dart';

/// A dropdown created from the list of addresses generated by the user
class NewAddressesDropdown extends StatefulWidget {
  /// Creates a new instance.
  const NewAddressesDropdown({
    required this._addresses,
    required this._selectedAddress,
    this._enabled = true,
    this._label,
    super.key,
  });
  final List<String> _addresses;
  final Widget? _label;
  final ValueNotifier<String> _selectedAddress;
  final bool _enabled;

  @override
  State<NewAddressesDropdown> createState() => _NewAddressesDropdownState();
}

class _NewAddressesDropdownState extends State<NewAddressesDropdown> {
  String get _address => widget._selectedAddress.value;

  final TextEditingController _searchController = TextEditingController();
  late String _selectedLabel;

  @override
  void initState() {
    super.initState();
    _selectedLabel = _labelFor(_address);
    widget._selectedAddress.addListener(_onSelectedAddressChanged);
  }

  @override
  Widget build(BuildContext context) {
    const Color color = AppColors.znnColor;

    final List<DropdownMenuEntry<String>> entries = widget._addresses
        .map(
          (String address) => DropdownMenuEntry<String>(
            label: _labelFor(address),
            style: MenuItemButton.styleFrom(
              foregroundColor: address == _address ? color : null,
            ),
            value: address,
          ),
        )
        .toList();

    return Focus(
      onFocusChange: (bool hasFocus) {
        if (!hasFocus) {
          _restoreSelectedLabel();
        }
      },
      child: DropdownMenu<String>(
        enabled: widget._enabled,
        controller: _searchController,
        enableFilter: true,
        expandedInsets: EdgeInsets.zero,
        filterCallback: _filterCallback,
        initialSelection: _address,
        inputDecorationTheme: const InputDecorationTheme(
          filled: true,
        ),
        label: widget._label,
        leadingIcon: const Icon(
          Icons.search,
          color: color,
        ),
        dropdownMenuEntries: entries,
        menuHeight: kDropdownMenuHeight,
        onSelected: (String? address) {
          if (address != null) {
            widget._selectedAddress.value = address;
          }
        },
        searchCallback: _searchCallback,
        textStyle: const TextStyle(
          color: color,
        ),
        trailingIcon: const Icon(
          Icons.keyboard_arrow_down_rounded,
          color: color,
        ),
      ),
    );
  }

  String _labelFor(String address) => kAddressLabelMap[address] ?? address;

  void _onSelectedAddressChanged() {
    setState(() {
      _selectedLabel = _labelFor(_address);
    });
    _restoreSelectedLabel();
  }

  void _restoreSelectedLabel() {
    _searchController.value = TextEditingValue(
      text: _selectedLabel,
      selection: TextSelection.collapsed(offset: _selectedLabel.length),
    );
  }

  int? _searchCallback(List<DropdownMenuEntry<String>> entries, String query) {
    final String searchText = query.toLowerCase();
    if (searchText.isEmpty) {
      return null;
    }
    final int index = entries.indexWhere(
      (DropdownMenuEntry<String> entry) => _matchTest(entry, searchText),
    );

    return index != -1 ? index : null;
  }

  List<DropdownMenuEntry<String>> _filterCallback(
    List<DropdownMenuEntry<String>> entries,
    String filter,
  ) {
    final String searchText = filter.toLowerCase();
    if (searchText.isEmpty) {
      return entries;
    }

    final Iterable<DropdownMenuEntry<String>> filtered = entries.where(
      (DropdownMenuEntry<String> entry) => _matchTest(entry, searchText),
    );

    return filtered.toList();
  }

  bool _matchTest(DropdownMenuEntry<String> entry, String searchText) =>
      entry.label.toLowerCase().contains(searchText) ||
      entry.value.toLowerCase().contains(searchText);

  @override
  void dispose() {
    widget._selectedAddress.removeListener(_onSelectedAddressChanged);
    _searchController.dispose();
    super.dispose();
  }
}
